name: Update AI IP Blocklist
on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  update_ips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch IPs with error handling
        run: |
          # X.ai/Grok (with fallback)
          curl -H "User-Agent: Mozilla/5.0" "https://ip-ranges.x.com/ip-ranges.json" | 
            jq -r '.prefixes[]?.ip_prefix' 2>/dev/null > xai_ips.txt || echo "# Failed X.ai" > xai_ips.txt
          
          # AWS (guaranteed to work)
          curl -s "https://ip-ranges.amazonaws.com/ip-ranges.json" | 
            jq -r '.prefixes[] | select(.service=="AMAZON") | .ip_prefix' > aws_ai_ips.txt
          
          # Google
          curl -s "https://www.gstatic.com/ipranges/goog.json" | 
            jq -r '.prefixes[] | .ipv4Prefix // .ipv6Prefix' | grep -v null > google_ai_ips.txt
          
          # Generate final IP list
          {
            echo "# === X.ai/Grok ==="
            [ -s xai_ips.txt ] && grep -v '^#' xai_ips.txt || echo "# No data"
            echo ""
            echo "# === AWS (OpenAI) ==="
            cat aws_ai_ips.txt
            echo ""
            echo "# === Google (Gemini) ==="
            cat google_ai_ips.txt
          } > IP_AI_list.txt
          
          # Debug output
          echo "=== Generated Files ==="
          ls -lah *.txt
          echo "IP_AI_list.txt content:"
          head -n 10 IP_AI_list.txt

      - name: Commit IPs
        run: |
          git config --global user.name "Automated Updater"
          git config --global user.email "actions@github.com"
          git add xai_ips.txt aws_ai_ips.txt google_ai_ips.txt IP_AI_list.txt
          git commit -m "IP update: $(date +'%Y-%m-%d')" || echo "No changes"
          git pull --rebase origin main
          git push origin main
